### ISSUE TITLE
Support dimod 0.10 for next `dwave-ocean-sdk` release

### ISSUE THREAD

**Issue by hhtong** [recruit-communications/pyqubo#100]
We are hoping to release a new version of [dwave-ocean-sdk](https://github.com/dwavesystems/dwave-ocean-sdk) that includes `dimod 0.10`. 

For this release to occur, we need to make sure that all the sdk packages support the new dimod, including `pyqubo`. The current upper bound set as `dimod<=0.10.0` would need to be raised to `<0.11`.

Thanks!

**Comment by randomir** [comment]
Hi @kotarotanahashi!

Any update on relaxing the upper bound for dimod 0.10?

We assume the current bound `<=0.10.0` is a typo. If it's not, then converting it to `<0.11` should be straightforward. Our latest dimod is 0.10.6 and there are no significant compatibility breaks since 0.10.0. OTOH, there are some major changes between 0.9.x and 0.10.x (check [release notes](https://github.com/dwavesystems/dimod/releases)).

Thanks!

**Comment by kotarotanahashi** [comment]
@randomir @hhtong Thank you for pointing this out. As you suggested, I'll revise it to `<0.11`.

Thanks!

**Comment by randomir** [comment]
If you could cut a (patch) release with this change as well, that would be great! Thanks!

**Comment by kotarotanahashi** [comment]
@randomir Yes, I already released a fixed version. Thank you!
