### ISSUE TITLE
Potential problem when using higher order polynomials?

### ISSUE THREAD

**Issue by weipengchen** [recruit-communications/pyqubo#43]
Dear Sir,

I ran into a problem when I use higher order polynomials in PyQUBO. I am not sure if the problem came from PyQUBO compilation function or dimod module. Here is the sample code and the result. Would you be able to check if you also see similar problem on your side?
========
from pyqubo import Binary, solve_qubo
x0, x1, x2, x3, x4 = Binary("x0"), Binary("x1"), Binary("x2"), Binary("x3"), Binary("x4")
H = x0 + x1 + x2 + x3 + x4 +  4*((1-x0)*(1-x1)*(1-x4) + (1-x2)*(1-x4) + 2*(1-x2)*(1-x3) + (1-x2)*(1-x3)*(1-x4))
model = H.compile()
qubo, offset = model.to_qubo()
solution = solve_qubo(qubo)
decoded_solution, broken, energy = model.decode_solution(solution, vartype='BINARY')
print("solution {}, broken {}, energy {}".format(decoded_solution, broken, energy))
======
Sometimes (not always) it generates negative energy shown as follows:
solution {'x0': 0, 'x1': 1, 'x2': 1, 'x3': 1, 'x4': 0}, broken {'AND(x2,x3)=x2*x3': {'result': {'x2': 1, 'x3': 1, 'x2*x3': 0}, 'penalty': 5.0}}, energy -4.0

The possible outcome of formulation H give binary inputs should be zero or positive value. Do you know why I get the negative energy value?

Thanks much for your help.

**Comment by kotarotanahashi** [comment]
@weipengchen Thank you for sharing the problem. I will investigate the issue with the code you provided.

**Comment by kotarotanahashi** [comment]
@weipengchen I'm sorry for the late response.  It looks like this behavior is not caused by library bugs. When the hamiltonian is converted to quadratic form, the Hamiltonian is not always positive when the constraint is broken. I explained it below step by step. I hope it helps.

(1) When the hamiltonian with higher order terms is compiled, first it is converted to expanded polynomial form. (I abbreviate the first linear terms `x0 + x1 + x2 + x3 + x4` for simplicity)
```
H = 4*((1-x0)(1-x1)(1-x4) + (1-x2)(1-x4) + 2(1-x2)(1-x3) + (1-x2)(1-x3)*(1-x4))
```
is converted to
```
H = 4*(-x0x1x4 + x0x4 - x0 + x1x4 -x1 + x0x1 -x2x3x4 + 3x2x3 + 2x2x4 - 4x2 + x3*x4 - 3x3 - 3*x4 + 5)
```
(2) Then, this polynomial is reduced to the quadratic form H' by introducing additional variables "x1*x4" and "x2*x4".
```
H' = H + strength * (P(x1, x4, x1*x4) + P(x2, x4, x2*x4))
```
where `P(a, b, c)=3c-2bc-2ac+ab` is a penalty function to ensure `a*b=c`. `strength` is a parameter.

In PyQUBO, H' is generated by
```
>>> H = 4*((1-x0)*(1-x1)*(1-x4) + (1-x2)*(1-x4) + 2*(1-x2)*(1-x3) + (1-x2)*(1-x3)*(1-x4))
>>> model = H.compile(strength=5.0)
>>> model.to_qubo()
({('x0', 'x1*x4'): -4.0,
  ('x0', 'x1'): 4.0,
  ('x0', 'x4'): 4.0,
  ('x1', 'x4'): 5.0,
  ('x1', 'x1*x4'): -10.0,
  ('x1*x4', 'x4'): -10.0,
  ('x2', 'x4'): 5.0,
  ('x2*x4', 'x4'): -10.0,
  ('x3', 'x4'): 4.0,
  ('x2', 'x2*x4'): -10.0,
  ('x2', 'x3'): 12.0,
  ('x2*x4', 'x3'): -4.0,
  ('x0', 'x0'): -4.0,
  ('x1', 'x1'): -4.0,
  ('x4', 'x4'): -12.0,
  ('x2', 'x2'): -16.0,
  ('x3', 'x3'): -12.0,
  ('x1*x4', 'x1*x4'): 19.0,
  ('x2*x4', 'x2*x4'): 23.0},
 20.0)
```

(3) For example, if you get the solution `{'x0': 0, 'x1': 1, 'x1*x4': 1, 'x2': 1, 'x2*x4': 0, 'x3': 0, 'x4': 1}` for the above QUBO, the energy is `-3`.
In this way, the negative energy appeared in your code. This behavior is very confusing so I would like to consider to provide warning if the constraint for binary product is broken when it is decoded.

**Comment by weipengchen** [comment]
@kotarotanahashi  Thanks much for your detailed explanation. By changing the parameter 'strength' I can get the correct answer.
